// import { BlackInfo, FriendApplicationInfo, FriendInfo, IFriendShipListener } from "imsdk";
//
// export class FriendShipListener implements IFriendShipListener {
//   onFriendApplicationAdded(friendApplication: FriendApplicationInfo): void{
//     console.error('==========================onFriendApplicationAdded',JSON.stringify(friendApplication))
//   };
//
//   onFriendApplicationDeleted(friendApplication: FriendApplicationInfo): void{
//     console.error('==========================onFriendApplicationDeleted',JSON.stringify(friendApplication))
//   };
//
//   onFriendApplicationAccepted(friendApplication: FriendApplicationInfo): void{
//     console.error('==========================onFriendApplicationAccepted',JSON.stringify(friendApplication))
//   };
//
//   onFriendApplicationRejected(friendApplication: FriendApplicationInfo): void{
//     console.error('==========================onFriendApplicationRejected',JSON.stringify(friendApplication))
//   };
//
//   onFriendAdded(friendInfo: FriendInfo): void{
//     console.error('==========================onFriendAdded',JSON.stringify(friendInfo))
//   };
//
//   onFriendDeleted(friendInfo: FriendInfo): void{
//     console.error('==========================onFriendDeleted',JSON.stringify(friendInfo))
//   };
//
//   onFriendInfoChanged(friendInfo: FriendInfo): void{
//     console.error('==========================onFriendInfoChanged',JSON.stringify(friendInfo))
//   };
//
//   onBlackAdded(blackInfo: BlackInfo): void{
//     console.error('==========================onBlackAdded',JSON.stringify(blackInfo))
//   };
//
//   onBlackDeleted(blackInfo: BlackInfo): void{
//     console.error('==========================onBlackDeleted',JSON.stringify(blackInfo))
//   };
// }