// import { Message } from 'imsdk';
// import { IMsgSendCallBack } from 'imsdk/src/main/ets/EventHandler';
//
// export class SendeventCallBack implements IMsgSendCallBack {
//   onError(code: number, errMsg: string):void {
//     console.error('+++++++++++++++++++++SendeventCallBack------onError',String(code),errMsg)
//   }
//   onSuccess(msg: Message):void {
//     console.error('+++++++++++++++++++++SendMsgCallBack------onSuccess',JSON.stringify(msg))
//   }
//   onProgress(progress: number):void {
//     console.error('+++++++++++++++++++++SendMsgCallBack------onProgress',progress)
//   }
// }